export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_ERROR = 'FETCH_TOPICS_ERROR';

export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_TOPIC_ARTICLES_REQUEST = 'FETCH_TOPIC_ARTICLES_REQUEST';
export const FETCH_TOPIC_ARTICLES_SUCCESS = 'FETCH_TOPIC_ARTICLES_SUCCESS';
export const FETCH_TOPIC_ARTICLES_ERROR = 'FETCH_TOPIC_ARTICLES_ERROR';

export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_ERROR = 'FETCH_ARTICLE_ERROR';

export const FETCH_ARTICLE_COMMENTS_REQUEST = 'FETCH_ARTICLE_COMMENTS_REQUEST';
export const FETCH_ARTICLE_COMMENTS_SUCCESS = 'FETCH_ARTICLE_COMMENTS_SUCCESS';
export const FETCH_ARTICLE_COMMENTS_ERROR = 'FETCH_ARTICLE_COMMENTS_ERROR';

export const ARTICLE_VOTE_REQUEST = 'ARTICLE_VOTE_REQUEST';
export const ARTICLE_VOTE_SUCCESS = 'ARTICLE_VOTE_SUCCESS';
export const ARTICLE_VOTE_ERROR = 'ARTICLE_VOTE_ERROR';

export const COMMENT_VOTE_REQUEST = 'COMMENT_VOTE_REQUEST';
export const COMMENT_VOTE_SUCCESS = 'COMMENT_VOTE_SUCCESS';
export const COMMENT_VOTE_ERROR = 'COMMENT_VOTE_ERROR';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR'

